# Test rendering of the chart with the controller explicitly set to StatefulSet and autoscaling enabled.
controller:
  type: statefulset
  autoscaling:
    enabled: true
    behavior: 
      scaleDown:
        selectPolicy: Disabled
agent:
  resources:
    requests:
      memory: 100Mi
