- name: Install grafana agent
  hosts: all
  become: true
  tasks:
    - name: "Prepare apt"
      when:
        - "ansible_pkg_mgr == 'apt'"
      block:
        - name: "Import Grafana apt gpg key"
          ansible.builtin.get_url:
            url: "https://apt.grafana.com/gpg.key"
            dest: /usr/share/keyrings/grafana.key
            mode: "0644"

        - name: "Add Grafana apt repository"
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com/ stable main"
            state: present
            update_cache: true

    - name: Install grafana-agent-flow
      ansible.builtin.apt:
        name: grafana-agent-flow
        state: present

    - name: Create /etc/grafana-agent-flow to store river files
      notify: "reload agent svc"
      ansible.builtin.file:
        path: /etc/grafana-agent-flow
        state: directory
        owner: grafana-agent-flow
        group: grafana-agent
        mode: '0744'

    - name: Create env file to set command line and config dir for grafana-agent-flow service
      notify: "reload agent svc"
      ansible.builtin.copy:
        src: environment-file
        dest: /etc/default/grafana-agent-flow
        mode: '0644'

    - name: Copy base config file
      notify: "reload agent svc"
      ansible.builtin.copy:
        src: configs/common.river
        owner: grafana-agent-flow
        group: grafana-agent
        dest: /etc/grafana-agent-flow/common.river
        mode: '0644'

    - name: Copy node exporter config
      notify: "reload agent svc"
      when:
        - "ansible_system == 'Linux'"
      ansible.builtin.copy:
        src: configs/unix.river
        owner: grafana-agent-flow
        group: grafana-agent
        dest: /etc/grafana-agent-flow/unix.river
        mode: '0644'
    
    - name: Enable grafana-agent-flow service
      ansible.builtin.service:
        name: grafana-agent-flow
        enabled: yes
        state: started
    
  handlers:
    - name: reload agent svc
      ansible.builtin.service:
        name: grafana-agent-flow
        state: reloaded
        daemon_reload: yes